services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - monitoring
    depends_on:
      - grafana
      - prometheus

  grafana:
    image: mqmqmqmq/cours:grafana
    build:
      context: .
      target: grafana_mq
    container_name: grafana
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    environment:
      - TZ=Europe/Paris
      - VIRTUAL_HOST=mqmqmqmq.duckdns.org
      - VIRTUAL_PORT=3000
      - GF_SERVER_ROOT_URL=http://mqmqmqmq.duckdns.org

  prometheus:
    image: mqmqmqmq/cours:prometheus
    build:
      context: .
      target: prometheus_mq
    container_name: prometheus
    restart: unless-stopped
    expose:
      - "9090"
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitoring
    environment:
      - TZ=Europe/Paris

  snmp-exporter:
    image: mqmqmqmq/cours:exporter
    build:
      context: .
      target: exporter_mq
    container_name: snmp-exporter
    restart: unless-stopped
    expose:
      - "9116"
    networks:
      - monitoring
    environment:
      - TZ=Europe/Paris

  router:
    image: mqmqmqmq/cours:frr-router
    build:
      context: .
      target: router_mq
    container_name: frr-router
    hostname: router1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      monitoring:
        ipv4_address: 192.168.100.10
    ports:
      - "161:161/udp"

networks:
  monitoring:
    name: monitoring
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  prometheus_data:
  grafana_data:
