global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'frr-router'
    scrape_interval: 30s
    static_configs:
      - targets:
          - 192.168.100.10
        labels:
          device: 'router1'
          vendor: 'frr'
          role: 'router'
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
